name: Print_Debug

on:
  issues:
    types:
      - closed

jobs:
  print_debug_info:
    runs-on: 'ubuntu-latest'
    steps:     
      - name: Debug - Placeholder
        run: |
          echo "${{github.event.pull_request.merged}}"

      - name: Debug - Github Event Context Info
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_EVENT"

      - name: Debug - Github Context Info
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{github.event.pull_request.merged}}"
          echo "$GITHUB_CONTEXT"

      - name: Debug - Envs
        run: env
