name: PrintEnv
run-name: ${{ github.event.repository.name }} by @${{ github.actor }}

# on:
#   push: 
on:
  issues:
    types:
      - closed

jobs:
  pass_in_secret_to_template:
    permissions:
      contents: read
      pull-requests: write
    uses: liulirun/github_workflow_template/.github/workflows/template_print_env.yml@main
    secrets: inherit
    
