name: 'Test Metrix'

on:
  push:
    branches: [stage, production]

jobs:

  create-terraform-plan:
    name: 'test-matrix'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        env:
            - dev
            - stage
              
    # runs-on: [self-hosted, Linux]
    defaults:
      run:
        shell: bash
        working-directory: "terraform/${{matrix.env}}"

    steps:         
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Echo
      run: |
        ls

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.0
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
