#test 1
name: Test_Trigger_Deployment_Trigger

# on:
#   push: 
on:
  issues:
    types:
      - closed
jobs:
  test_trigger_env:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo "test_trigger_env"
  
  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: test_trigger_env
    steps:
      - run: |
          echo "deploy-dev"
    
  deploy-staging:
    runs-on: 'ubuntu-latest'
    environment: 'staging'
    needs: [test_trigger_env, deploy-dev]
    steps:
      - run: |
          echo "deploy-staging"

#TODO:  add label