name: Test_Trigger_Lable

on:
  pull_request:
    types:
      - labeled

jobs:
  test_trigger:
    if: ${{ github.event.label.name == 'dev' }} || ${{ github.event.label.name == 'stage' }} || ${{ github.event.label.name == 'production' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "env is : ${{ github.event.label.name }}"
